name: Node.js CI

on:
  push:
    branches:
      - master
      - develop
      - release
  pull_request:
    branches:
      - master
      - develop
      - release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: |
        cd client
        npm install
    - run: |
        cd client
        npm run build --if-present
    - run: |
        cd client
        npm test
      env:
        CI: true